cores = {'laranja': '\033[33m', 'branco': '\033[30m', 'vermelho': '\033[31m', 'amarelo': '\033[32m', 'azul': '\033[34m', 'roxo': '\033[35m', 'ciano': '\033[36m', 'cinza': '\033[37m'}
back = {'limpa': '\033[m', 'branco': '\033[40m', 'vermelho': '\033[41m', 'amarelo': '\033[42m', 'laranja': '\033[43m', 'azul': '\033[44m', 'roxo': '\033[45m', 'ciano': '\033[46m', 'cinza': '\033[47m'}
print('{}Branco'.format(cores['branco']))
print('{}Laranja'.format(cores['laranja']))
print('{}Amarelo'.format(cores['amarelo']))
print('{}Vermelho'.format(cores['vermelho']))
print('{}Azul'.format(cores['azul']))
print('{}Roxo'.format(cores['roxo']))
print('{}Ciano'.format(cores['ciano']))
print('{}Cinza'.format(cores['cinza']))
print('{}   {} Branco'.format(back['branco'], back['limpa']))
print('{}   {} Vermelho'.format(back['vermelho'], back['limpa']))
print('{}   {} Amarelo'.format(back['amarelo'], back['limpa']))
print('{}   {} Laranja'.format(back['laranja'], back['limpa']))
print('{}   {} Azul'.format(back['azul'], back['limpa']))
print('{}   {} Roxo'.format(back['roxo'], back['limpa']))
print('{}   {} Ciano'.format(back['ciano'], back['limpa']))
print('{}   {} Cinza'.format(back['cinza'], back['limpa']))
