# Faça um programa que leia um numero inteiro e mostre na tela sua tabuada
print('\n{:*^40}\n'.format('Desafio009'))
n = int(input('Digite um numero: '))
print('Tabuada de {}' .format(n))
print(n, ' x  1 =  {}' .format(n * 1))
print(n, ' x  2 =  {}' .format(n * 2))
print(n, ' x  3 =  {}' .format(n * 3))
print(n, ' x  4 =  {}' .format(n * 4))
print(n, ' x  5 =  {}' .format(n * 5))
print(n, ' x  6 =  {}' .format(n * 6))
print(n, ' x  7 =  {}' .format(n * 7))
print(n, ' x  8 =  {}' .format(n * 8))
print(n, ' x  9 =  {}' .format(n * 9))
print(n, ' x 10 =  {}' .format(n * 10))
print('\n{:*^40}\n'.format('FIM'))
