n = input('Digite algo: ')
print('O tipo primitivo é', type(n))
print('É um numero: ', n.isnumeric())
print('É um alfanumerico: ', n.isalnum())
print('Só tem letras: ', n.isalpha())
print('Esta capitalizada: ', n.istitle())
print('Esta em maiusculo: ', n.isupper())
print('Esta em minusculo: ', n.islower())
print('Só tem espaços: ', n.isspace())
